// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Category struct {
	ID        int64
	UserID    int64
	Name      string
	Emoji     string
	SortOrder sql.NullInt64
}

type Expense struct {
	ID         int64
	UserID     int64
	CategoryID int64
	Amount     float64
	Note       sql.NullString
	CreatedAt  sql.NullTime
}

type User struct {
	ID           int64
	TelegramID   int64
	Name         string
	Timezone     sql.NullString
	DailySummary sql.NullBool
	CreatedAt    sql.NullTime
}
