// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, emoji, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, name, emoji, sort_order
`

type CreateCategoryParams struct {
	UserID    int64
	Name      string
	Emoji     string
	SortOrder sql.NullInt64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Emoji,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.SortOrder,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, amount, note)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, category_id, amount, note, created_at
`

type CreateExpenseParams struct {
	UserID     int64
	CategoryID int64
	Amount     float64
	Note       sql.NullString
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_id, name)
VALUES (?, ?)
ON CONFLICT(telegram_id) DO UPDATE SET name=excluded.name
RETURNING id, telegram_id, name, timezone, daily_summary, created_at
`

type CreateUserParams struct {
	TelegramID int64
	Name       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.TelegramID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Timezone,
		&i.DailySummary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ? AND user_id = ?
`

type DeleteCategoryParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, emoji, sort_order FROM categories
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Emoji,
		&i.SortOrder,
	)
	return i, err
}

const getExpensesForUserByDateRange = `-- name: GetExpensesForUserByDateRange :many
SELECT e.id, e.user_id, e.category_id, e.amount, e.note, e.created_at, c.name as category_name, c.emoji as category_emoji
FROM expenses e
JOIN categories c ON e.category_id = c.id
WHERE e.user_id = ? AND date(e.created_at) >= date(?) AND date(e.created_at) <= date(?)
ORDER BY e.created_at DESC
`

type GetExpensesForUserByDateRangeParams struct {
	UserID int64
	Date   interface{}
	Date_2 interface{}
}

type GetExpensesForUserByDateRangeRow struct {
	ID            int64
	UserID        int64
	CategoryID    int64
	Amount        float64
	Note          sql.NullString
	CreatedAt     sql.NullTime
	CategoryName  string
	CategoryEmoji string
}

func (q *Queries) GetExpensesForUserByDateRange(ctx context.Context, arg GetExpensesForUserByDateRangeParams) ([]GetExpensesForUserByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesForUserByDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpensesForUserByDateRangeRow
	for rows.Next() {
		var i GetExpensesForUserByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpensesForToday = `-- name: GetTotalExpensesForToday :one
SELECT coalesce(SUM(amount), 0.0) as total
FROM expenses
WHERE user_id = ? AND date(created_at, 'localtime') = date('now', 'localtime')
`

func (q *Queries) GetTotalExpensesForToday(ctx context.Context, userID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpensesForToday, userID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalExpensesForUserByDateRange = `-- name: GetTotalExpensesForUserByDateRange :one
SELECT coalesce(SUM(amount), 0.0) as total
FROM expenses
WHERE user_id = ? AND date(created_at) >= date(?) AND date(created_at) <= date(?)
`

type GetTotalExpensesForUserByDateRangeParams struct {
	UserID int64
	Date   interface{}
	Date_2 interface{}
}

func (q *Queries) GetTotalExpensesForUserByDateRange(ctx context.Context, arg GetTotalExpensesForUserByDateRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpensesForUserByDateRange, arg.UserID, arg.Date, arg.Date_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, name, timezone, daily_summary, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Timezone,
		&i.DailySummary,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, name, timezone, daily_summary, created_at FROM users
WHERE telegram_id = ? LIMIT 1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Timezone,
		&i.DailySummary,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoriesForUser = `-- name: ListCategoriesForUser :many
SELECT id, user_id, name, emoji, sort_order FROM categories
WHERE user_id = ?
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListCategoriesForUser(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Emoji,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForDailySummary = `-- name: ListUsersForDailySummary :many
SELECT id, telegram_id, name, timezone, daily_summary, created_at FROM users
WHERE daily_summary = 1
`

func (q *Queries) ListUsersForDailySummary(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForDailySummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Name,
			&i.Timezone,
			&i.DailySummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserConfig = `-- name: UpdateUserConfig :exec
UPDATE users
SET timezone = ?, daily_summary = ?
WHERE id = ?
`

type UpdateUserConfigParams struct {
	Timezone     sql.NullString
	DailySummary sql.NullBool
	ID           int64
}

func (q *Queries) UpdateUserConfig(ctx context.Context, arg UpdateUserConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateUserConfig, arg.Timezone, arg.DailySummary, arg.ID)
	return err
}
